# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
collections:
  articles:
    output: true
    permalink: /articles/:path/index.html
    yoh: yeah
    categories:
      - reference
      - guides
markdown: HTMLPipeline
html_pipeline:
  filters:
    - "markdownfilter"
    - "sanitizationfilter"
    - "imagemaxwidthfilter"
    - "tableofcontentsfilter"
    - "syntaxhighlightfilter"
    # - "extendedmarkdownfilter"
    - "autolinkfilter"
redcarpet:
  extensions:
  - fenced_code_blocks
gems:
  - jekyll-html-pipeline
  - sanitize
  - pygments.rb
  # - extended-markdown-filter
  # - github-linguist
  # - github-markdown
