# Site settings
title: Help
email: support@packager.io
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/help" # the subpath of your site, e.g. /blog/
url: "https://packager.io" # the base hostname & protocol for your site
twitter_username: hellopkgr
github_username:  pkgr
collections:
  articles:
    output: true
    permalink: /:path/index.html
    categories:
      - reference
      - guides

# Build settings
markdown: HTMLPipeline
html_pipeline:
  filters:
    - "markdownfilter"
    - "sanitizationfilter"
    - "imagemaxwidthfilter"
    - "tableofcontentsfilter"
    - "syntaxhighlightfilter"
    # - "extendedmarkdownfilter"
    - "autolinkfilter"
redcarpet:
  extensions:
  - fenced_code_blocks
gems:
  - jekyll-html-pipeline
  - sanitize
  - pygments.rb
  - redcarpet
  # - extended-markdown-filter
  - linguist
  - github/markdown
