# Site settings
title: Help
email: support@packager.io
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/help" # the subpath of your site, e.g. /blog/
url: "https://packager.io" # the base hostname & protocol for your site
twitter_username: hellopkgr
github_username:  pkgr
collections:
  articles:
    output: true
    permalink: /:path/index.html
    categories:
      - getting-started
      - reference
      - guides

# Build settings
markdown: HTMLPipeline
html_pipeline:
  filters:
    # - "sanitizationfilter"
    - "ExtendedMarkdownFilter"
    - "imagemaxwidthfilter"
    - "AddCssClassToTableFilter"
    - "tableofcontentsfilter"
    - "syntaxhighlightfilter"
    - "autolinkfilter"
  context:
    emf_use_blocks: true
redcarpet:
  extensions:
  - fenced_code_blocks
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: articles
  values:
    layout: doc
gems:
  - jekyll-html-pipeline
  - sanitize
  - pygments.rb
  - redcarpet
  - extended-markdown-filter
  - linguist
  - github/markdown
  - jekyll-autolink_email
